### ISSUE TITLE
Component ignores changes to props

### ISSUE THREAD

**Issue by 42shadow42** [CeamKrier/react-editable-title#11]
If the callback or other props are changed, the changes are ignored because memoization ignores prop values.

**Comment by CeamKrier** [comment]
Hey @42shadow42 

Thanks for reporting. Seems like I messed up with the memorization there. I'll provide a working soliton on a separate branch in a few mins.

**Comment by CeamKrier** [comment]
Ahoy @42shadow42 

I'm merging the branch, if you come across with any issue please don't hesitate to re-open the issue.
