### ISSUE TITLE
react-editable-title incompatible with latest versions of next-js

### ISSUE THREAD

**Issue by 42shadow42** [CeamKrier/react-editable-title#6]
Because this node module imports global css it is incompatible with next-js.

./node_modules/react-editable-title/src/css/index.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules\react-editable-title\lib\index.js

**Comment by CeamKrier** [comment]
Hey,
Thanks for reporting. I'll check it tomorrow.

**Comment by 42shadow42** [comment]
@CeamKrier I almost have a fix for it if that helps any. I'm not sure if it qualifies as extensive changes because it is using bundling via rollup for the distributable.

**Comment by 42shadow42** [comment]
@CeamKrier I opened a pull request to fix this. https://github.com/CeamKrier/react-editable-title/pull/7

**Comment by CeamKrier** [comment]
Added the line-height back to buttons https://github.com/CeamKrier/react-editable-title/pull/7#issuecomment-624968734
