### ISSUE TITLE
Dimensions of seamless input become 0 after editing

### ISSUE THREAD

**Issue by 42shadow42** [CeamKrier/react-editable-title#9]
When two seamless inputs are side by side, I noticed that you can generate overlap between the inputs by editing the left most input.

To replicate you can add merge the columns with fields for the hondaModel and year. After editing the model the year input will collapse on top of the model input.

It appears the problem lies in calculate dimensions retrieving the wrong dimensions.

	const calculateDimensions = useMemo(() => {
		return {
			width: displayTextRef.current?.offsetWidth,
			height: displayTextRef.current?.offsetHeight,
		};
	}, [editing]);

I was able to remove the bug by removing the function and style references to it, but don't know if there are any negative implications of removing this obviously intentional code.

**Comment by CeamKrier** [comment]
Hey @42shadow42 

Thanks for reporting. I have taken a look at the issue and I guess resolved it. Before merging it to master can you have look at it? It is at the `overlap-fix` branch.

**Comment by 42shadow42** [comment]
I'm still seeing the issue: Here is a copy of my showcase.tsx
[showcase.txt](https://github.com/CeamKrier/react-editable-title/files/4606323/showcase.txt)

`

**Comment by CeamKrier** [comment]
The code you sent works fine. Have you built the project before testing it?
![image](https://user-images.githubusercontent.com/18554425/81506587-0c11d600-9300-11ea-85dc-5618615959b7.png)

**Comment by 42shadow42** [comment]
You are right, the bug is fixed.
